server:
  port: 8881
  servlet:
    context-path: /mgBoot
#spring:
#  profiles:
#    active: prod1
---

server:
  port: 8882 
spring:
  profiles: dev1
  
---

server:
  port: 8883 
spring:
  profiles: prod1









#person: 
#  last-name: 芬琪
#  age: 25
#  maps: {work: 数据分析师,love: 名桂}
#  list: 
#    - 可爱
#    - 有追求